export interface BlogPost {
  id: number;
  title: string;
  category: string;
  description: string;
  content: string;
  banner: string;
  date: string;
}

export const mockPosts: BlogPost[] = [{
  id: 1,
  title: 'the brown fox jumps over the lazy dog',
  category: 'Categoria',
  description: 'Pulvinar arcu faucibus pretium fermentum, dolor, adipiscing interdum ac aliquam. Amet massa eget id in ipsum, accumsan, volutpat. Turpis elit aliquet faucibus enim egestas scelerisque neque pellentesque. Vel tristique fames sed mattis. Dignissim mattis gravida euismod eget odio eu odio. Leo egestas viverra leo placerat sit. At aenean vulputate ridiculus tincidunt. Felis pretium imperdiet at arcu. Quam aliquam nisl diam laoreet fringilla rutrum tempus. Ac tristique ultrices purus velit eget facilisis in varius ipsum. Cursus feugiat volutpat pharetra, blandit leo arcu id purus donec. Vulputate ultricies neque scelerisque risus dictumst et. Integer mi, varius velit lacus, donec urna tincidunt. Egestas iaculis ligula adipiscing tempor. Dignissim scelerisque ornare tristique blandit nulla.',
  content: `<p>Egestas amet risus massa congue in sem amet. Tellus sagittis scelerisque mi cursus. Vel egestas pellentesque in elit fermentum gravida. Sodales vel quam vulputate turpis ullamcorper nulla rhoncus. Fringilla eu dolor tristique orci, ornare senectus nisi, morbi in. Id tincidunt lectus nunc gravida nisl dui. Mauris, nec egestas in sem blandit phasellus et. Pretium tellus sit semper turpis bibendum fringilla suspendisse tincidunt justo. Ornare feugiat tortor luctus in. Mollis vulputate mattis at ultricies dictum habitasse tellus non nibh. Scelerisque malesuada a enim enim sollicitudin lobortis purus. Arcu arcu molestie sagittis nec. Posuere tellus sit sed tristique eget massa lectus. Viverra elementum, adipiscing tristique elementum convallis ornare.
  Id purus facilisi eleifend tristique. Sed adipiscing et tempor sed egestas amet. </p>Dolor mauris ultricies quam bibendum nam. Auctor tristique pellentesque tempor est est enim adipiscing viverra. Vulputate aliquam risus sit eget sit in. Eu morbi leo pretium purus est. Nibh purus quam nibh vestibulum. Urna lectus hac urna accumsan purus volutpat, hendrerit eget. Mauris posuere eget metus lacus, et eu ac velit. Mauris suspendisse pellentesque pulvinar a, gravida turpis vitae, gravida. Lacus, turpis posuere scelerisque aliquam eu, phasellus tincidunt gravida. Magna auctor ut imperdiet at ultricies at quam a. Tempor commodo id felis molestie cursus erat.
  Dolor est elementum ac, risus. Ultricies euismod rhoncus ultricies dui tortor fusce pellentesque lorem. Euismod nisi tristique tristique scelerisque enim, ut vestibulum malesuada mattis. Eros nunc, id nisl egestas ipsum semper urna, tempor. Est ac aliquet tincidunt velit. Malesuada eu eget malesuada facilisi sed amet vulputate lorem.
  Nulla sem enim vitae, sit. Elit senectus tristique commodo arcu. Elit vestibulum non suspendisse ornare nulla ut et nam ac. Quis pharetra integer pellentesque viverra. Nec mauris vulputate praesent vel pellentesque gravida vel eu. Diam quisque mattis commodo sodales condimentum. Id urna, purus porta proin eleifend diam sed. Convallis id venenatis semper augue mauris blandit sed egestas est. Ullamcorper vestibulum cras turpis donec tempor. Fames ultrices condimentum risus laoreet tellus. Pulvinar dui diam sapien eget bibendum ultrices potenti fames.`,
  banner: 'https://www.cellmax.eu/wp-content/uploads/2020/01/Hero-Banner-Placeholder-Dark-1024x480-1.png',
  date: '12/23/2022',
},
{
  id: 2,
  title: 'the brown fox jumps over the lazy dog',
  category: 'Categoria',
  description: 'Pulvinar arcu faucibus pretium fermentum, dolor, adipiscing interdum ac aliquam. Amet massa eget id in ipsum, accumsan, volutpat. Turpis elit aliquet faucibus enim egestas scelerisque neque pellentesque. Vel tristique fames sed mattis. Dignissim mattis gravida euismod eget odio eu odio. Leo egestas viverra leo placerat sit. At aenean vulputate ridiculus tincidunt. Felis pretium imperdiet at arcu. Quam aliquam nisl diam laoreet fringilla rutrum tempus. Ac tristique ultrices purus velit eget facilisis in varius ipsum. Cursus feugiat volutpat pharetra, blandit leo arcu id purus donec. Vulputate ultricies neque scelerisque risus dictumst et. Integer mi, varius velit lacus, donec urna tincidunt. Egestas iaculis ligula adipiscing tempor. Dignissim scelerisque ornare tristique blandit nulla.',
  content: `Egestas amet risus massa congue in sem amet. Tellus sagittis scelerisque mi cursus. Vel egestas pellentesque in elit fermentum gravida. Sodales vel quam vulputate turpis ullamcorper nulla rhoncus. Fringilla eu dolor tristique orci, ornare senectus nisi, morbi in. Id tincidunt lectus nunc gravida nisl dui. Mauris, nec egestas in sem blandit phasellus et. Pretium tellus sit semper turpis bibendum fringilla suspendisse tincidunt justo. Ornare feugiat tortor luctus in. Mollis vulputate mattis at ultricies dictum habitasse tellus non nibh. Scelerisque malesuada a enim enim sollicitudin lobortis purus. Arcu arcu molestie sagittis nec. Posuere tellus sit sed tristique eget massa lectus. Viverra elementum, adipiscing tristique elementum convallis ornare.
  Id purus facilisi eleifend tristique. Sed adipiscing et tempor sed egestas amet. Dolor mauris ultricies quam bibendum nam. Auctor tristique pellentesque tempor est est enim adipiscing viverra. Vulputate aliquam risus sit eget sit in. Eu morbi leo pretium purus est. Nibh purus quam nibh vestibulum. Urna lectus hac urna accumsan purus volutpat, hendrerit eget. Mauris posuere eget metus lacus, et eu ac velit. Mauris suspendisse pellentesque pulvinar a, gravida turpis vitae, gravida. Lacus, turpis posuere scelerisque aliquam eu, phasellus tincidunt gravida. Magna auctor ut imperdiet at ultricies at quam a. Tempor commodo id felis molestie cursus erat.
  Dolor est elementum ac, risus. Ultricies euismod rhoncus ultricies dui tortor fusce pellentesque lorem. Euismod nisi tristique tristique scelerisque enim, ut vestibulum malesuada mattis. Eros nunc, id nisl egestas ipsum semper urna, tempor. Est ac aliquet tincidunt velit. Malesuada eu eget malesuada facilisi sed amet vulputate lorem.
  Nulla sem enim vitae, sit. Elit senectus tristique commodo arcu. Elit vestibulum non suspendisse ornare nulla ut et nam ac. Quis pharetra integer pellentesque viverra. Nec mauris vulputate praesent vel pellentesque gravida vel eu. Diam quisque mattis commodo sodales condimentum. Id urna, purus porta proin eleifend diam sed. Convallis id venenatis semper augue mauris blandit sed egestas est. Ullamcorper vestibulum cras turpis donec tempor. Fames ultrices condimentum risus laoreet tellus. Pulvinar dui diam sapien eget bibendum ultrices potenti fames.`,
  banner: 'https://www.cellmax.eu/wp-content/uploads/2020/01/Hero-Banner-Placeholder-Dark-1024x480-1.png',
  date: '12/23/2022',
},
{
  id: 3,
  title: 'the brown fox jumps over the lazy dog',
  category: 'Categoria',
  description: 'Pulvinar arcu faucibus pretium fermentum, dolor, adipiscing interdum ac aliquam. Amet massa eget id in ipsum, accumsan, volutpat. Turpis elit aliquet faucibus enim egestas scelerisque neque pellentesque. Vel tristique fames sed mattis. Dignissim mattis gravida euismod eget odio eu odio. Leo egestas viverra leo placerat sit. At aenean vulputate ridiculus tincidunt. Felis pretium imperdiet at arcu. Quam aliquam nisl diam laoreet fringilla rutrum tempus. Ac tristique ultrices purus velit eget facilisis in varius ipsum. Cursus feugiat volutpat pharetra, blandit leo arcu id purus donec. Vulputate ultricies neque scelerisque risus dictumst et. Integer mi, varius velit lacus, donec urna tincidunt. Egestas iaculis ligula adipiscing tempor. Dignissim scelerisque ornare tristique blandit nulla.',
  content: `Egestas amet risus massa congue in sem amet. Tellus sagittis scelerisque mi cursus. Vel egestas pellentesque in elit fermentum gravida. Sodales vel quam vulputate turpis ullamcorper nulla rhoncus. Fringilla eu dolor tristique orci, ornare senectus nisi, morbi in. Id tincidunt lectus nunc gravida nisl dui. Mauris, nec egestas in sem blandit phasellus et. Pretium tellus sit semper turpis bibendum fringilla suspendisse tincidunt justo. Ornare feugiat tortor luctus in. Mollis vulputate mattis at ultricies dictum habitasse tellus non nibh. Scelerisque malesuada a enim enim sollicitudin lobortis purus. Arcu arcu molestie sagittis nec. Posuere tellus sit sed tristique eget massa lectus. Viverra elementum, adipiscing tristique elementum convallis ornare.
  Id purus facilisi eleifend tristique. Sed adipiscing et tempor sed egestas amet. Dolor mauris ultricies quam bibendum nam. Auctor tristique pellentesque tempor est est enim adipiscing viverra. Vulputate aliquam risus sit eget sit in. Eu morbi leo pretium purus est. Nibh purus quam nibh vestibulum. Urna lectus hac urna accumsan purus volutpat, hendrerit eget. Mauris posuere eget metus lacus, et eu ac velit. Mauris suspendisse pellentesque pulvinar a, gravida turpis vitae, gravida. Lacus, turpis posuere scelerisque aliquam eu, phasellus tincidunt gravida. Magna auctor ut imperdiet at ultricies at quam a. Tempor commodo id felis molestie cursus erat.
  Dolor est elementum ac, risus. Ultricies euismod rhoncus ultricies dui tortor fusce pellentesque lorem. Euismod nisi tristique tristique scelerisque enim, ut vestibulum malesuada mattis. Eros nunc, id nisl egestas ipsum semper urna, tempor. Est ac aliquet tincidunt velit. Malesuada eu eget malesuada facilisi sed amet vulputate lorem.
  Nulla sem enim vitae, sit. Elit senectus tristique commodo arcu. Elit vestibulum non suspendisse ornare nulla ut et nam ac. Quis pharetra integer pellentesque viverra. Nec mauris vulputate praesent vel pellentesque gravida vel eu. Diam quisque mattis commodo sodales condimentum. Id urna, purus porta proin eleifend diam sed. Convallis id venenatis semper augue mauris blandit sed egestas est. Ullamcorper vestibulum cras turpis donec tempor. Fames ultrices condimentum risus laoreet tellus. Pulvinar dui diam sapien eget bibendum ultrices potenti fames.`,
  banner: 'https://www.cellmax.eu/wp-content/uploads/2020/01/Hero-Banner-Placeholder-Dark-1024x480-1.png',
  date: '12/23/2022',
},
{
  id: 4,
  title: 'the brown fox jumps over the lazy dog',
  category: 'Categoria',
  description: 'Pulvinar arcu faucibus pretium fermentum, dolor, adipiscing interdum ac aliquam. Amet massa eget id in ipsum, accumsan, volutpat. Turpis elit aliquet faucibus enim egestas scelerisque neque pellentesque. Vel tristique fames sed mattis. Dignissim mattis gravida euismod eget odio eu odio. Leo egestas viverra leo placerat sit. At aenean vulputate ridiculus tincidunt. Felis pretium imperdiet at arcu. Quam aliquam nisl diam laoreet fringilla rutrum tempus. Ac tristique ultrices purus velit eget facilisis in varius ipsum. Cursus feugiat volutpat pharetra, blandit leo arcu id purus donec. Vulputate ultricies neque scelerisque risus dictumst et. Integer mi, varius velit lacus, donec urna tincidunt. Egestas iaculis ligula adipiscing tempor. Dignissim scelerisque ornare tristique blandit nulla.',
  content: `Egestas amet risus massa congue in sem amet. Tellus sagittis scelerisque mi cursus. Vel egestas pellentesque in elit fermentum gravida. Sodales vel quam vulputate turpis ullamcorper nulla rhoncus. Fringilla eu dolor tristique orci, ornare senectus nisi, morbi in. Id tincidunt lectus nunc gravida nisl dui. Mauris, nec egestas in sem blandit phasellus et. Pretium tellus sit semper turpis bibendum fringilla suspendisse tincidunt justo. Ornare feugiat tortor luctus in. Mollis vulputate mattis at ultricies dictum habitasse tellus non nibh. Scelerisque malesuada a enim enim sollicitudin lobortis purus. Arcu arcu molestie sagittis nec. Posuere tellus sit sed tristique eget massa lectus. Viverra elementum, adipiscing tristique elementum convallis ornare.
  Id purus facilisi eleifend tristique. Sed adipiscing et tempor sed egestas amet. Dolor mauris ultricies quam bibendum nam. Auctor tristique pellentesque tempor est est enim adipiscing viverra. Vulputate aliquam risus sit eget sit in. Eu morbi leo pretium purus est. Nibh purus quam nibh vestibulum. Urna lectus hac urna accumsan purus volutpat, hendrerit eget. Mauris posuere eget metus lacus, et eu ac velit. Mauris suspendisse pellentesque pulvinar a, gravida turpis vitae, gravida. Lacus, turpis posuere scelerisque aliquam eu, phasellus tincidunt gravida. Magna auctor ut imperdiet at ultricies at quam a. Tempor commodo id felis molestie cursus erat.
  Dolor est elementum ac, risus. Ultricies euismod rhoncus ultricies dui tortor fusce pellentesque lorem. Euismod nisi tristique tristique scelerisque enim, ut vestibulum malesuada mattis. Eros nunc, id nisl egestas ipsum semper urna, tempor. Est ac aliquet tincidunt velit. Malesuada eu eget malesuada facilisi sed amet vulputate lorem.
  Nulla sem enim vitae, sit. Elit senectus tristique commodo arcu. Elit vestibulum non suspendisse ornare nulla ut et nam ac. Quis pharetra integer pellentesque viverra. Nec mauris vulputate praesent vel pellentesque gravida vel eu. Diam quisque mattis commodo sodales condimentum. Id urna, purus porta proin eleifend diam sed. Convallis id venenatis semper augue mauris blandit sed egestas est. Ullamcorper vestibulum cras turpis donec tempor. Fames ultrices condimentum risus laoreet tellus. Pulvinar dui diam sapien eget bibendum ultrices potenti fames.`,
  banner: 'https://www.cellmax.eu/wp-content/uploads/2020/01/Hero-Banner-Placeholder-Dark-1024x480-1.png',
  date: '12/23/2022',
},
{
  id: 5,
  title: 'the brown fox jumps over the lazy dog',
  category: 'Categoria',
  description: 'Pulvinar arcu faucibus pretium fermentum, dolor, adipiscing interdum ac aliquam. Amet massa eget id in ipsum, accumsan, volutpat. Turpis elit aliquet faucibus enim egestas scelerisque neque pellentesque. Vel tristique fames sed mattis. Dignissim mattis gravida euismod eget odio eu odio. Leo egestas viverra leo placerat sit. At aenean vulputate ridiculus tincidunt. Felis pretium imperdiet at arcu. Quam aliquam nisl diam laoreet fringilla rutrum tempus. Ac tristique ultrices purus velit eget facilisis in varius ipsum. Cursus feugiat volutpat pharetra, blandit leo arcu id purus donec. Vulputate ultricies neque scelerisque risus dictumst et. Integer mi, varius velit lacus, donec urna tincidunt. Egestas iaculis ligula adipiscing tempor. Dignissim scelerisque ornare tristique blandit nulla.',
  content: `Egestas amet risus massa congue in sem amet. Tellus sagittis scelerisque mi cursus. Vel egestas pellentesque in elit fermentum gravida. Sodales vel quam vulputate turpis ullamcorper nulla rhoncus. Fringilla eu dolor tristique orci, ornare senectus nisi, morbi in. Id tincidunt lectus nunc gravida nisl dui. Mauris, nec egestas in sem blandit phasellus et. Pretium tellus sit semper turpis bibendum fringilla suspendisse tincidunt justo. Ornare feugiat tortor luctus in. Mollis vulputate mattis at ultricies dictum habitasse tellus non nibh. Scelerisque malesuada a enim enim sollicitudin lobortis purus. Arcu arcu molestie sagittis nec. Posuere tellus sit sed tristique eget massa lectus. Viverra elementum, adipiscing tristique elementum convallis ornare.
  Id purus facilisi eleifend tristique. Sed adipiscing et tempor sed egestas amet. Dolor mauris ultricies quam bibendum nam. Auctor tristique pellentesque tempor est est enim adipiscing viverra. Vulputate aliquam risus sit eget sit in. Eu morbi leo pretium purus est. Nibh purus quam nibh vestibulum. Urna lectus hac urna accumsan purus volutpat, hendrerit eget. Mauris posuere eget metus lacus, et eu ac velit. Mauris suspendisse pellentesque pulvinar a, gravida turpis vitae, gravida. Lacus, turpis posuere scelerisque aliquam eu, phasellus tincidunt gravida. Magna auctor ut imperdiet at ultricies at quam a. Tempor commodo id felis molestie cursus erat.
  Dolor est elementum ac, risus. Ultricies euismod rhoncus ultricies dui tortor fusce pellentesque lorem. Euismod nisi tristique tristique scelerisque enim, ut vestibulum malesuada mattis. Eros nunc, id nisl egestas ipsum semper urna, tempor. Est ac aliquet tincidunt velit. Malesuada eu eget malesuada facilisi sed amet vulputate lorem.
  Nulla sem enim vitae, sit. Elit senectus tristique commodo arcu. Elit vestibulum non suspendisse ornare nulla ut et nam ac. Quis pharetra integer pellentesque viverra. Nec mauris vulputate praesent vel pellentesque gravida vel eu. Diam quisque mattis commodo sodales condimentum. Id urna, purus porta proin eleifend diam sed. Convallis id venenatis semper augue mauris blandit sed egestas est. Ullamcorper vestibulum cras turpis donec tempor. Fames ultrices condimentum risus laoreet tellus. Pulvinar dui diam sapien eget bibendum ultrices potenti fames.`,
  banner: 'https://www.cellmax.eu/wp-content/uploads/2020/01/Hero-Banner-Placeholder-Dark-1024x480-1.png',
  date: '12/23/2022',
},
{
  id: 6,
  title: 'the brown fox jumps over the lazy dog',
  category: 'Categoria',
  description: 'Pulvinar arcu faucibus pretium fermentum, dolor, adipiscing interdum ac aliquam. Amet massa eget id in ipsum, accumsan, volutpat. Turpis elit aliquet faucibus enim egestas scelerisque neque pellentesque. Vel tristique fames sed mattis. Dignissim mattis gravida euismod eget odio eu odio. Leo egestas viverra leo placerat sit. At aenean vulputate ridiculus tincidunt. Felis pretium imperdiet at arcu. Quam aliquam nisl diam laoreet fringilla rutrum tempus. Ac tristique ultrices purus velit eget facilisis in varius ipsum. Cursus feugiat volutpat pharetra, blandit leo arcu id purus donec. Vulputate ultricies neque scelerisque risus dictumst et. Integer mi, varius velit lacus, donec urna tincidunt. Egestas iaculis ligula adipiscing tempor. Dignissim scelerisque ornare tristique blandit nulla.',
  content: `Egestas amet risus massa congue in sem amet. Tellus sagittis scelerisque mi cursus. Vel egestas pellentesque in elit fermentum gravida. Sodales vel quam vulputate turpis ullamcorper nulla rhoncus. Fringilla eu dolor tristique orci, ornare senectus nisi, morbi in. Id tincidunt lectus nunc gravida nisl dui. Mauris, nec egestas in sem blandit phasellus et. Pretium tellus sit semper turpis bibendum fringilla suspendisse tincidunt justo. Ornare feugiat tortor luctus in. Mollis vulputate mattis at ultricies dictum habitasse tellus non nibh. Scelerisque malesuada a enim enim sollicitudin lobortis purus. Arcu arcu molestie sagittis nec. Posuere tellus sit sed tristique eget massa lectus. Viverra elementum, adipiscing tristique elementum convallis ornare.
  Id purus facilisi eleifend tristique. Sed adipiscing et tempor sed egestas amet. Dolor mauris ultricies quam bibendum nam. Auctor tristique pellentesque tempor est est enim adipiscing viverra. Vulputate aliquam risus sit eget sit in. Eu morbi leo pretium purus est. Nibh purus quam nibh vestibulum. Urna lectus hac urna accumsan purus volutpat, hendrerit eget. Mauris posuere eget metus lacus, et eu ac velit. Mauris suspendisse pellentesque pulvinar a, gravida turpis vitae, gravida. Lacus, turpis posuere scelerisque aliquam eu, phasellus tincidunt gravida. Magna auctor ut imperdiet at ultricies at quam a. Tempor commodo id felis molestie cursus erat.
  Dolor est elementum ac, risus. Ultricies euismod rhoncus ultricies dui tortor fusce pellentesque lorem. Euismod nisi tristique tristique scelerisque enim, ut vestibulum malesuada mattis. Eros nunc, id nisl egestas ipsum semper urna, tempor. Est ac aliquet tincidunt velit. Malesuada eu eget malesuada facilisi sed amet vulputate lorem.
  Nulla sem enim vitae, sit. Elit senectus tristique commodo arcu. Elit vestibulum non suspendisse ornare nulla ut et nam ac. Quis pharetra integer pellentesque viverra. Nec mauris vulputate praesent vel pellentesque gravida vel eu. Diam quisque mattis commodo sodales condimentum. Id urna, purus porta proin eleifend diam sed. Convallis id venenatis semper augue mauris blandit sed egestas est. Ullamcorper vestibulum cras turpis donec tempor. Fames ultrices condimentum risus laoreet tellus. Pulvinar dui diam sapien eget bibendum ultrices potenti fames.`,
  banner: 'https://www.cellmax.eu/wp-content/uploads/2020/01/Hero-Banner-Placeholder-Dark-1024x480-1.png',
  date: '12/23/2022',
},
{
  id: 7,
  title: 'the brown fox jumps over the lazy dog',
  category: 'Categoria',
  description: 'Pulvinar arcu faucibus pretium fermentum, dolor, adipiscing interdum ac aliquam. Amet massa eget id in ipsum, accumsan, volutpat. Turpis elit aliquet faucibus enim egestas scelerisque neque pellentesque. Vel tristique fames sed mattis. Dignissim mattis gravida euismod eget odio eu odio. Leo egestas viverra leo placerat sit. At aenean vulputate ridiculus tincidunt. Felis pretium imperdiet at arcu. Quam aliquam nisl diam laoreet fringilla rutrum tempus. Ac tristique ultrices purus velit eget facilisis in varius ipsum. Cursus feugiat volutpat pharetra, blandit leo arcu id purus donec. Vulputate ultricies neque scelerisque risus dictumst et. Integer mi, varius velit lacus, donec urna tincidunt. Egestas iaculis ligula adipiscing tempor. Dignissim scelerisque ornare tristique blandit nulla.',
  content: `Egestas amet risus massa congue in sem amet. Tellus sagittis scelerisque mi cursus. Vel egestas pellentesque in elit fermentum gravida. Sodales vel quam vulputate turpis ullamcorper nulla rhoncus. Fringilla eu dolor tristique orci, ornare senectus nisi, morbi in. Id tincidunt lectus nunc gravida nisl dui. Mauris, nec egestas in sem blandit phasellus et. Pretium tellus sit semper turpis bibendum fringilla suspendisse tincidunt justo. Ornare feugiat tortor luctus in. Mollis vulputate mattis at ultricies dictum habitasse tellus non nibh. Scelerisque malesuada a enim enim sollicitudin lobortis purus. Arcu arcu molestie sagittis nec. Posuere tellus sit sed tristique eget massa lectus. Viverra elementum, adipiscing tristique elementum convallis ornare.
  Id purus facilisi eleifend tristique. Sed adipiscing et tempor sed egestas amet. Dolor mauris ultricies quam bibendum nam. Auctor tristique pellentesque tempor est est enim adipiscing viverra. Vulputate aliquam risus sit eget sit in. Eu morbi leo pretium purus est. Nibh purus quam nibh vestibulum. Urna lectus hac urna accumsan purus volutpat, hendrerit eget. Mauris posuere eget metus lacus, et eu ac velit. Mauris suspendisse pellentesque pulvinar a, gravida turpis vitae, gravida. Lacus, turpis posuere scelerisque aliquam eu, phasellus tincidunt gravida. Magna auctor ut imperdiet at ultricies at quam a. Tempor commodo id felis molestie cursus erat.
  Dolor est elementum ac, risus. Ultricies euismod rhoncus ultricies dui tortor fusce pellentesque lorem. Euismod nisi tristique tristique scelerisque enim, ut vestibulum malesuada mattis. Eros nunc, id nisl egestas ipsum semper urna, tempor. Est ac aliquet tincidunt velit. Malesuada eu eget malesuada facilisi sed amet vulputate lorem.
  Nulla sem enim vitae, sit. Elit senectus tristique commodo arcu. Elit vestibulum non suspendisse ornare nulla ut et nam ac. Quis pharetra integer pellentesque viverra. Nec mauris vulputate praesent vel pellentesque gravida vel eu. Diam quisque mattis commodo sodales condimentum. Id urna, purus porta proin eleifend diam sed. Convallis id venenatis semper augue mauris blandit sed egestas est. Ullamcorper vestibulum cras turpis donec tempor. Fames ultrices condimentum risus laoreet tellus. Pulvinar dui diam sapien eget bibendum ultrices potenti fames.`,
  banner: 'https://www.cellmax.eu/wp-content/uploads/2020/01/Hero-Banner-Placeholder-Dark-1024x480-1.png',
  date: '12/23/2022',
},
{
  id: 8,
  title: 'the brown fox jumps over the lazy dog',
  category: 'Categoria',
  description: 'Pulvinar arcu faucibus pretium fermentum, dolor, adipiscing interdum ac aliquam. Amet massa eget id in ipsum, accumsan, volutpat. Turpis elit aliquet faucibus enim egestas scelerisque neque pellentesque. Vel tristique fames sed mattis. Dignissim mattis gravida euismod eget odio eu odio. Leo egestas viverra leo placerat sit. At aenean vulputate ridiculus tincidunt. Felis pretium imperdiet at arcu. Quam aliquam nisl diam laoreet fringilla rutrum tempus. Ac tristique ultrices purus velit eget facilisis in varius ipsum. Cursus feugiat volutpat pharetra, blandit leo arcu id purus donec. Vulputate ultricies neque scelerisque risus dictumst et. Integer mi, varius velit lacus, donec urna tincidunt. Egestas iaculis ligula adipiscing tempor. Dignissim scelerisque ornare tristique blandit nulla.',
  content: `Egestas amet risus massa congue in sem amet. Tellus sagittis scelerisque mi cursus. Vel egestas pellentesque in elit fermentum gravida. Sodales vel quam vulputate turpis ullamcorper nulla rhoncus. Fringilla eu dolor tristique orci, ornare senectus nisi, morbi in. Id tincidunt lectus nunc gravida nisl dui. Mauris, nec egestas in sem blandit phasellus et. Pretium tellus sit semper turpis bibendum fringilla suspendisse tincidunt justo. Ornare feugiat tortor luctus in. Mollis vulputate mattis at ultricies dictum habitasse tellus non nibh. Scelerisque malesuada a enim enim sollicitudin lobortis purus. Arcu arcu molestie sagittis nec. Posuere tellus sit sed tristique eget massa lectus. Viverra elementum, adipiscing tristique elementum convallis ornare.
  Id purus facilisi eleifend tristique. Sed adipiscing et tempor sed egestas amet. Dolor mauris ultricies quam bibendum nam. Auctor tristique pellentesque tempor est est enim adipiscing viverra. Vulputate aliquam risus sit eget sit in. Eu morbi leo pretium purus est. Nibh purus quam nibh vestibulum. Urna lectus hac urna accumsan purus volutpat, hendrerit eget. Mauris posuere eget metus lacus, et eu ac velit. Mauris suspendisse pellentesque pulvinar a, gravida turpis vitae, gravida. Lacus, turpis posuere scelerisque aliquam eu, phasellus tincidunt gravida. Magna auctor ut imperdiet at ultricies at quam a. Tempor commodo id felis molestie cursus erat.
  Dolor est elementum ac, risus. Ultricies euismod rhoncus ultricies dui tortor fusce pellentesque lorem. Euismod nisi tristique tristique scelerisque enim, ut vestibulum malesuada mattis. Eros nunc, id nisl egestas ipsum semper urna, tempor. Est ac aliquet tincidunt velit. Malesuada eu eget malesuada facilisi sed amet vulputate lorem.
  Nulla sem enim vitae, sit. Elit senectus tristique commodo arcu. Elit vestibulum non suspendisse ornare nulla ut et nam ac. Quis pharetra integer pellentesque viverra. Nec mauris vulputate praesent vel pellentesque gravida vel eu. Diam quisque mattis commodo sodales condimentum. Id urna, purus porta proin eleifend diam sed. Convallis id venenatis semper augue mauris blandit sed egestas est. Ullamcorper vestibulum cras turpis donec tempor. Fames ultrices condimentum risus laoreet tellus. Pulvinar dui diam sapien eget bibendum ultrices potenti fames.`,
  banner: 'https://www.cellmax.eu/wp-content/uploads/2020/01/Hero-Banner-Placeholder-Dark-1024x480-1.png',
  date: '12/23/2022',
},
{
  id: 9,
  title: 'the brown fox jumps over the lazy dog',
  category: 'Categoria',
  description: 'Pulvinar arcu faucibus pretium fermentum, dolor, adipiscing interdum ac aliquam. Amet massa eget id in ipsum, accumsan, volutpat. Turpis elit aliquet faucibus enim egestas scelerisque neque pellentesque. Vel tristique fames sed mattis. Dignissim mattis gravida euismod eget odio eu odio. Leo egestas viverra leo placerat sit. At aenean vulputate ridiculus tincidunt. Felis pretium imperdiet at arcu. Quam aliquam nisl diam laoreet fringilla rutrum tempus. Ac tristique ultrices purus velit eget facilisis in varius ipsum. Cursus feugiat volutpat pharetra, blandit leo arcu id purus donec. Vulputate ultricies neque scelerisque risus dictumst et. Integer mi, varius velit lacus, donec urna tincidunt. Egestas iaculis ligula adipiscing tempor. Dignissim scelerisque ornare tristique blandit nulla.',
  content: `Egestas amet risus massa congue in sem amet. Tellus sagittis scelerisque mi cursus. Vel egestas pellentesque in elit fermentum gravida. Sodales vel quam vulputate turpis ullamcorper nulla rhoncus. Fringilla eu dolor tristique orci, ornare senectus nisi, morbi in. Id tincidunt lectus nunc gravida nisl dui. Mauris, nec egestas in sem blandit phasellus et. Pretium tellus sit semper turpis bibendum fringilla suspendisse tincidunt justo. Ornare feugiat tortor luctus in. Mollis vulputate mattis at ultricies dictum habitasse tellus non nibh. Scelerisque malesuada a enim enim sollicitudin lobortis purus. Arcu arcu molestie sagittis nec. Posuere tellus sit sed tristique eget massa lectus. Viverra elementum, adipiscing tristique elementum convallis ornare.
  Id purus facilisi eleifend tristique. Sed adipiscing et tempor sed egestas amet. Dolor mauris ultricies quam bibendum nam. Auctor tristique pellentesque tempor est est enim adipiscing viverra. Vulputate aliquam risus sit eget sit in. Eu morbi leo pretium purus est. Nibh purus quam nibh vestibulum. Urna lectus hac urna accumsan purus volutpat, hendrerit eget. Mauris posuere eget metus lacus, et eu ac velit. Mauris suspendisse pellentesque pulvinar a, gravida turpis vitae, gravida. Lacus, turpis posuere scelerisque aliquam eu, phasellus tincidunt gravida. Magna auctor ut imperdiet at ultricies at quam a. Tempor commodo id felis molestie cursus erat.
  Dolor est elementum ac, risus. Ultricies euismod rhoncus ultricies dui tortor fusce pellentesque lorem. Euismod nisi tristique tristique scelerisque enim, ut vestibulum malesuada mattis. Eros nunc, id nisl egestas ipsum semper urna, tempor. Est ac aliquet tincidunt velit. Malesuada eu eget malesuada facilisi sed amet vulputate lorem.
  Nulla sem enim vitae, sit. Elit senectus tristique commodo arcu. Elit vestibulum non suspendisse ornare nulla ut et nam ac. Quis pharetra integer pellentesque viverra. Nec mauris vulputate praesent vel pellentesque gravida vel eu. Diam quisque mattis commodo sodales condimentum. Id urna, purus porta proin eleifend diam sed. Convallis id venenatis semper augue mauris blandit sed egestas est. Ullamcorper vestibulum cras turpis donec tempor. Fames ultrices condimentum risus laoreet tellus. Pulvinar dui diam sapien eget bibendum ultrices potenti fames.`,
  banner: 'https://www.cellmax.eu/wp-content/uploads/2020/01/Hero-Banner-Placeholder-Dark-1024x480-1.png',
  date: '12/23/2022',
}];

export const mockCategories = [
  'category 1',
  'category 2',
  'category 3',
  'category 4',
  'category 5',
]