export const CONTRIBUTORS = [
  'Alan Silva Costa',
  'Alexandre Vasconcelos',
  'Álvaro Dornelles Hetzel',
  'Amanda Lie Kitagava',
  'Ana Luiza Santos Terra',
  'Andre Assumpcao',
  'Augusto Pascutti',
  'Bruno Englert Moutinho',
  'Caio Werneck',
  'Danilo Amaral de OLiveira',
  'Dreyf Assis Gonçalves',
  'Eduardo Carvalho Rosa',
  'Felipe Geremia Nievinski',
  'Frank Farias Santos',
  'George Antonio Vilas Boas Santiago',
  'Gustavo Brondani Schenkel',
  'Henrique Lorea Leite',
  'Igor Bandim',
  'Isadora Queiroz',
  'José Antônio Ribeiro Vargas',
  'Jose Guilherme Vanz',
  'Juliano De Holanda Freitas',
  'Kelsen Henrique',
  'Louise Pereira',
  'Marco Guedes',
  'Maria Victoria Ferraz',
  'Mário Rutman',
  'Mario Santos Silva',
  'Mércia Maguerroski',
  'Paulo Costa',
  'Paulo Henrique Franzon',
  'Pedro Guedes',
  'Rafael ROsado Urquhart',
  'Rafael Toledo',
  'Renato Rebelo de Moraes',
  'Ricardo Fernandes de Souza',
  'Vítor Márcio Paiva de Sousa Baptista',
  'Natássya Barlate Floro da Silva',
  'Guilherme R. Storck',
  'Francisco Goldmeier Tochetto',
  "Thiago Sant' Helena",
  'Débora Maria Valverde da Silva',
  'Murilo Viana',
  'Vinícius Monteiro',
];