export const REPOSITORIES = [
  'José Guilherme Vanz',
  'Irio Musskopf',
  'Renne Rocha',
  'Giovani Sousa Leite',
  'Eduardo Cuducos',
  'Antonio Vendramin',
  'Giulio Carvalho',
  'Bruno Lellis',
  'Danilo Jeremias da Silva',
  'Rodolfo Lottin Pereira',
  'Victor Torres',
  'Alan Fachini',
  'Vitor Baptista',
  'Pedro Garcias',
  'Felipe Ruhland',
  'Helder Geovane Gomes de Lima',
  'Alvaro Leonel',
  'Ana Paula Gomes',
  'Fábio C. Barrionuevo da Luz',
  'Adorilson Bezerra',
  'Weibe Moura',
  'Beothorn',
  'Anderson Berg',
  'Bruna Moreira',
  'Jeferson Alves',
  'Hugo Leonardo Costa e Silva',
  'Beothorn',
  'Anderson Berg',
  'Bruna Moreira',
  'Jeferson Alves',
  'Hugo Leonardo Costa e Silva',
  'Thiago Curvelo',
  'Vinicius Artur',
  'Rodrigo Vieira',
  'Avelino',
  'Gustavo De Mari Pereira',
  'Laerte Pereira',
  'Camila Fracaro',
  'Jonathan Schweder',
  'Gustavo Coelho',
  'André Angeluci',
  'Lucas Santos Summer',
  'Pedro Peixoto',
  'Rodrigo Chamun',
  'Enderson Menezes',
  'Nícolas F. R. A. Prado',
  'Vinicius Gasparini',
  'Gabriel Trette',
  'Paulo Henrique Cuchi',
  'Chico Venancio',
  'Daiana Marasquin',
  'Jonathan Cardoso',
  'Lucas Rangel Cezimbra',
  'Gabriel (Gabu) Bellon',
  'Mohan Sha',
  'Alexandre Vicenzi',
  'Rodrigo Lima',
];
